<a href="https://colab.research.google.com/github/nkonreddy/LLM/blob/main/Chap00_Intro_to_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

In [ ]:
!pip install -qq torch==2.4.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 797.2/797.2 MB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 90.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 68.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 34.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2

In [ ]:
import torch
torch.__version__

'2.4.0+cu121'

In [ ]:
torch.cuda.is_available()

False

# Tensors

## Dimensions

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/6.webp" width="400px">

In [ ]:
tensor0d = torch.tensor(2)
tensor0d

tensor(1)

In [ ]:
tensor1d = torch.tensor([3, 1, 3])
tensor1d

tensor([3, 1, 3])

In [ ]:
tensor2d = torch.tensor([[3,5,1,2], [1, 7, 2, 3], [3, 3, 4, 9]])
tensor2d

tensor([[3, 5, 1, 2],
        [1, 7, 2, 3],
        [3, 3, 4, 9]])

In [ ]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
tensor3d = torch.tensor([
                            [[1, 2, 3], [4, 5, 6]],
                            [[1, 2, 3], [4, 5, 6]],
                            [[11, 12, 13], [14, 15, 16]],
                            [[17, 18, 19], [20, 21, 22]]
                        ])
tensor3d

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])

## Dtype

In [ ]:
tensor2d.dtype

torch.int64

In [ ]:
tensorfloat = torch.tensor([1.0, 2.0, 3.0])
tensorfloat.dtype

torch.float32

In [ ]:
tensorfloat64 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
tensorfloat64.dtype

torch.float64

In [ ]:
tensorfloat64.to(torch.float16)

tensor([1., 2., 3.], dtype=torch.float16)

## Operations

### Shape

In [ ]:
tensor0d.shape

torch.Size([])

In [ ]:
tensor1d.shape

torch.Size([3])

In [ ]:
tensor2d.shape

torch.Size([2, 3])

In [ ]:
tensor3d.shape

torch.Size([4, 2, 3])

### Reshape

In [ ]:
tensor2d.shape

torch.Size([2, 3])

In [ ]:
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
tensor2dmod = tensor2d.reshape(3,2)
tensor2dmod.shape

torch.Size([3, 2])

In [ ]:
print(tensor2dmod)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


### View

In [ ]:
tensor2d.view([2,3])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
tensor2d.view([3,2])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
import torch

x = torch.randn(2, 4, 8)
print(x)
z = x[:, ::2, :4]
print(z)
try:
    z.view(-1)
except RuntimeError as e:
    print(e)

tensor([[[-1.1783,  0.9491, -1.2084,  0.3899, -2.1687, -0.3752,  0.3077,
           1.5953],
         [-0.7747,  0.0223, -0.8280,  0.6586, -0.6978,  1.0346,  0.9350,
          -0.4206],
         [ 0.9525,  0.5167,  0.6550, -0.4758, -1.3071,  1.2405,  0.2837,
          -0.4108],
         [ 0.9740,  0.6944, -1.3363,  0.4708, -1.4802,  0.8807, -0.8606,
          -0.8628]],

        [[ 2.1550, -0.2373, -0.5731, -0.3742, -0.5123,  2.4566,  0.7939,
          -0.2927],
         [-0.3534,  0.2462,  0.3657,  0.4103, -0.1639, -1.9083, -0.4377,
          -1.1254],
         [-0.6756,  0.5493, -0.1976, -0.5780,  0.4622,  0.2773,  0.5538,
          -0.9195],
         [-0.1972,  0.5253, -1.0295, -0.4545,  0.0807,  0.7435, -0.7228,
          -0.6517]]])
tensor([[[-1.1783,  0.9491, -1.2084,  0.3899],
         [ 0.9525,  0.5167,  0.6550, -0.4758]],

        [[ 2.1550, -0.2373, -0.5731, -0.3742],
         [-0.6756,  0.5493, -0.1976, -0.5780]]])
view size is not compatible with input tensor's size and str

### Transpose

In [ ]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### Unsqueeze

In [ ]:
# create two dimensional tensor
a = torch.tensor([[2,3], [1,2]])
print(a)
a.dtype

tensor([[2, 3],
        [1, 2]])


torch.int64

In [ ]:
a = torch.Tensor([[2,3], [1,2]])
print(a)
a.dtype

tensor([[2., 3.],
        [1., 2.]])


torch.float32

In [ ]:
# insert Unsqueeze

### MatMul

In [ ]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [ ]:
tensor2d @ tensor2d.T   # short hand notation

tensor([[14, 32],
        [32, 77]])

# Differentiation Engine

https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

## Forward Pass

In [ ]:
import torch.nn.functional as F

y = torch.Tensor([1])
x1 = torch.Tensor([1.1])
w1 = torch.Tensor([2.2])
b = torch.Tensor([0])
z = x1 * w1 + b
print(z)

tensor([2.4200])


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/7.webp" width="600px">

In [ ]:
a = torch.sigmoid(z)
print(a)

tensor([0.9183])


In [ ]:
loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


## Calculate Gradient

In [ ]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)
z = x1 * w1 + b
print(z)

tensor([2.4200], grad_fn=<AddBackward0>)


In [ ]:
a = torch.sigmoid(z)
print(a)
loss = F.binary_cross_entropy(a, y)
print(loss)

tensor([0.9183], grad_fn=<SigmoidBackward0>)
tensor(0.0852, grad_fn=<BinaryCrossEntropyBackward0>)


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/8.webp" width="600px">

In [ ]:
grad_l_w1 = grad(loss, w1, retain_graph=True) # retain it, otherwise it is deleted.
print(grad_l_w1)

(tensor([-0.0898]),)


In [ ]:
grad_l_b = grad(loss, b, retain_graph=True)
print(grad_l_b)

(tensor([-0.0817]),)


In [ ]:
loss.backward()
w1.grad

tensor([-0.0898])

In [ ]:
b.grad

tensor([-0.0817])

# NeuralNetwork

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/9.webp" width="500px">

In [ ]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, input_size, output_size):
        super(NeuralNetwork, self).__init__()
        self.input_size = input_size
        self.output_size = output_size
        self.layers = torch.nn.Sequential(
            # first layer
            torch.nn.Linear(self.input_size, 30),
            torch.nn.ReLU(),

            # second layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # output layer
            torch.nn.Linear(20, self.output_size),
        )

    def forward(self, x):
        logits = self.layers(x) # outputs of last layers are called logits
        return logits





In [ ]:
model = NeuralNetwork(input_size=50, output_size=3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [ ]:
[p.numel() for p in model.parameters() ]

[1500, 30, 600, 20, 60, 3]

In [ ]:
[p.numel() for p in model.parameters() if p.requires_grad]

[1500, 30, 600, 20, 60, 3]

In [ ]:
[p for p in model.parameters() if p.requires_grad]

[Parameter containing:
 tensor([[-0.0808, -0.0824, -0.0365,  ..., -0.0199,  0.0257, -0.0194],
         [-0.1117,  0.0209, -0.0512,  ..., -0.0116, -0.0783, -0.1375],
         [ 0.1320,  0.1054, -0.0187,  ...,  0.1368, -0.1326,  0.0796],
         ...,
         [ 0.1066,  0.1250, -0.1092,  ...,  0.0645,  0.0209,  0.0207],
         [ 0.0766,  0.0322, -0.0621,  ...,  0.1061,  0.0820, -0.0216],
         [-0.1034, -0.0518,  0.1225,  ...,  0.0784,  0.0910, -0.0808]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0642, -0.0877, -0.0065,  0.0415, -0.1187, -0.0199,  0.1021,  0.0360,
          0.0898,  0.0899, -0.0918,  0.0624,  0.0792, -0.0357, -0.0891, -0.0687,
          0.0613, -0.0339,  0.1253, -0.1057, -0.0042,  0.1309, -0.0633, -0.0651,
         -0.1215, -0.0318, -0.1096, -0.0131, -0.0563, -0.1032],
        requires_grad=True),
 Parameter containing:
 tensor([[ 8.8508e-02, -1.7788e-01,  1.6722e-01, -1.2712e-01, -9.6625e-03,
          -1.6247e-01,  1.5982e-01, -1.5673e-01,  

In [ ]:
# number of trainable parameters
sum([p.numel() for p in model.parameters() if p.requires_grad])

2213

In [ ]:
model.layers[0].weight

Parameter containing:
tensor([[-0.0808, -0.0824, -0.0365,  ..., -0.0199,  0.0257, -0.0194],
        [-0.1117,  0.0209, -0.0512,  ..., -0.0116, -0.0783, -0.1375],
        [ 0.1320,  0.1054, -0.0187,  ...,  0.1368, -0.1326,  0.0796],
        ...,
        [ 0.1066,  0.1250, -0.1092,  ...,  0.0645,  0.0209,  0.0207],
        [ 0.0766,  0.0322, -0.0621,  ...,  0.1061,  0.0820, -0.0216],
        [-0.1034, -0.0518,  0.1225,  ...,  0.0784,  0.0910, -0.0808]],
       requires_grad=True)

In [ ]:
model.layers[0].weight.shape

torch.Size([30, 50])

In [ ]:
model.layers[0].bias

Parameter containing:
tensor([ 0.0642, -0.0877, -0.0065,  0.0415, -0.1187, -0.0199,  0.1021,  0.0360,
         0.0898,  0.0899, -0.0918,  0.0624,  0.0792, -0.0357, -0.0891, -0.0687,
         0.0613, -0.0339,  0.1253, -0.1057, -0.0042,  0.1309, -0.0633, -0.0651,
        -0.1215, -0.0318, -0.1096, -0.0131, -0.0563, -0.1032],
       requires_grad=True)

In [ ]:
model.layers[0].bias.shape

torch.Size([30])

## Try the model

In [ ]:
torch.manual_seed(123)
X = torch.randn(1, 50)
print(X)

tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603, -0.2196, -0.3792,
          0.7671, -1.1925,  0.6984, -1.4097,  0.1794,  1.8951,  0.4954,  0.2692,
         -0.0770, -1.0205, -0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010,
          0.4965, -1.5723,  0.9666, -1.1481, -1.1589,  0.3255, -0.6315, -2.8400,
         -1.3250,  0.1784, -1.4779,  1.1331, -1.2203,  1.3139,  1.0533,  0.1388,
         -0.2044, -2.2685, -0.2808,  0.7697, -0.6596, -0.7979,  0.1838,  0.2293,
          0.6177, -0.2876]])


In [ ]:
out = model(X)
out

tensor([[-0.1178,  0.1198, -0.1133]], grad_fn=<AddmmBackward0>)


# Data Loaders

## Create Datasets

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/10.webp" width="600px">

In [ ]:
X_train = torch.tensor([[-1.2, 3.1], [-0.9, 2.9], [-0.5, 2.6], [2.3, -1.1], [2.7, -1.5]])
y_train = torch.tensor([0, 0, 0, 1, 1])

X_test = torch.tensor([[-0.8, 2.8], [2.6, -1.6]])
y_test = torch.tensor([0, 1])



In [ ]:
from torch.utils.data import Dataset

class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]


In [ ]:
train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)
train_ds

## Create Dataloaders

In [ ]:
from torch.utils.data import DataLoader

train_dl = DataLoader(train_ds, batch_size=2, shuffle=True, num_workers=0, drop_last=True)
test_dl = DataLoader(test_ds, batch_size=2)

In [ ]:
for batch in train_dl:
    print(batch)

[tensor([[-1.2000,  3.1000],
        [ 2.3000, -1.1000]]), tensor([0, 1])]
[tensor([[-0.9000,  2.9000],
        [ 2.7000, -1.5000]]), tensor([0, 1])]


## Training Loop

In [ ]:
import torch
import torch.nn.functional as F
from torch.autograd import grad
from torch.utils.data import Dataset, DataLoader

In [ ]:
torch.manual_seed(123)
model = NeuralNetwork(input_size=2, output_size=2)
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

In [ ]:
num_epochs = 3
for epoch in range(num_epochs):
    model.train()
    for idx, (features, labels) in enumerate(train_dl):
        y_pred = model(features)
        loss = F.cross_entropy(y_pred, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f"\tEpoch: {epoch}, Batch: {idx}, Loss: {loss.item()}")
    model.eval()
    with torch.no_grad():
        for idx, (features, labels) in enumerate(test_dl):
            y_pred = model(features)
            loss = loss_fn(y_pred, labels)
            print(f"Epoch: {epoch}, Batch: {idx}, Loss: {loss.item()}")

	Epoch: 0, Batch: 0, Loss: 0.7487356662750244
	Epoch: 0, Batch: 1, Loss: 0.6450306177139282
Epoch: 0, Batch: 0, Loss: 0.25006431341171265
	Epoch: 1, Batch: 0, Loss: 0.253987193107605
	Epoch: 1, Batch: 1, Loss: 0.11282707750797272
Epoch: 1, Batch: 0, Loss: 0.04952475428581238
	Epoch: 2, Batch: 0, Loss: 0.057810522615909576
	Epoch: 2, Batch: 1, Loss: 0.03357567638158798
Epoch: 2, Batch: 0, Loss: 0.016697168350219727


## Evaluation

In [ ]:
model.eval()
with torch.no_grad():
    outputs = model(X_train)
    print(outputs)
    _, predicted = torch.max(outputs, 1)
    print(predicted)

tensor([[ 2.0769, -3.2128],
        [ 1.8213, -2.8764],
        [ 1.4636, -2.4074],
        [-1.6386,  1.6361],
        [-1.9006,  1.9140]])
tensor([0, 0, 0, 1, 1])


In [ ]:
probas = torch.softmax(outputs, dim=1)
print(probas)

tensor([[0.9950, 0.0050],
        [0.9910, 0.0090],
        [0.9796, 0.0204],
        [0.0364, 0.9636],
        [0.0216, 0.9784]])


In [ ]:
predictions = torch.argmax(probas, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [ ]:
predictions == y_train

tensor([True, True, True, True, True])

In [ ]:
def compute_accuracy(model, dataloader):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for idx, (features, labels) in enumerate(dataloader):
            outputs = model(features)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    return correct / total

compute_accuracy(model, train_dl)

1.0

In [ ]:
compute_accuracy(model, test_dl)

1.0

## Save Model

In [ ]:
torch.save(model.state_dict(), 'model.pth')
!ls -alh

total 24K
drwxr-xr-x 1 root root 4.0K Dec 10 01:52 .
drwxr-xr-x 1 root root 4.0K Dec 10 01:47 ..
drwxr-xr-x 4 root root 4.0K Dec  6 14:21 .config
-rw-r--r-- 1 root root 5.4K Dec 10 01:52 model.pth
drwxr-xr-x 1 root root 4.0K Dec  6 14:22 sample_data


## Load Model

In [ ]:
model.load_state_dict(torch.load('model.pth'))
model

<ipython-input-68-899586179785>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('model.pth'))


NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=2, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=2, bias=True)
  )
)